### ISSUE TITLE
Support DNS

### ISSUE THREAD

**Issue by cawoodm** [pinojs/pino-socket#18]
It seems this library only works with IP addresses and not hostnames. Could we get Hostname/DNS support?

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Mogztter** [comment]
I cannot reproduce this issue, I can use `localhost` or `foobar`:


```console
$ cat /etc/hosts
127.0.0.1	foobar
```

It also works using `tcpbin.com:4242`. I'm using Node v16.16.0.
