### ISSUE TITLE
Syslog Format Support

### ISSUE THREAD

**Issue by cawoodm** [pinojs/pino-socket#19]
It seems this tool blindly passes stdin to the UDP port without formatting messages for syslog - is that correct?

Syslog format: `<PRIO>TIMESTAMP HOST MESSAGE`

When we feed pino-socket output into logstash it is saying the format is invalid.

**Comment by jsumners** [comment]
> It seems this tool blindly passes stdin to the UDP port without formatting messages for syslog - is that correct?

Yes, that is correct. This module is for forwarding data to a socket. Nothing else.

See https://github.com/pinojs/pino-syslog
