### ISSUE TITLE
Is `close` a valid Writable stream option?

### ISSUE THREAD

**Issue by jarrodconnolly** [pinojs/pino-socket#38]
I may be reading this incorrectly but wanted to double-check with an issue before opening a PR.

Looking at the creation of the Writable stream in both the TCP and UDP connections I am wondering if the correct option is being used here:

https://github.com/pinojs/pino-socket/blob/master/lib/TcpConnection.js#L44

https://github.com/pinojs/pino-socket/blob/master/lib/UdpConnection.js#L17

It does not appear that `close` is a valid option for a Writable stream.
https://nodejs.org/dist/latest-v14.x/docs/api/stream.html#stream_new_stream_writable_options

Are these meant to be `destroy` or `final`?

Thank you for any thoughts or clarifications.

**Comment by mcollina** [comment]
Good spot! I think that option is useless and actually not needed.

Wdyt @Eomm ?

**Comment by Eomm** [comment]
Yes, I think it should be replaced with `destroy` to close the socket gracefully

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
