### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino-socket#59]
See #57 and the other other PRs.
I'm a bit strained with time so it would be awesome if somebody else could take a look.

**Comment by jsumners** [comment]
I know that I technically have all the free time I'm ever going to get to work on stuff, and I'm going to try to do so, but I'm having a hard time doing so. I'll try at some point though.

**Comment by mcollina** [comment]
Would you like to send a PR to thread-stream?

**Comment by ramonmulia** [comment]
To fix CI, needs a pino with `thread-stream@0.15.1`, there is a PR opened to update it https://github.com/pinojs/pino/pull/1382

**Comment by mcollina** [comment]
There is no need to bump the dependency, that's not how semver and npm work.

**Comment by jsumners** [comment]
Resolved.
