### ISSUE TITLE
Process exits with code 0 even with underlying exception

### ISSUE THREAD

**Issue by marcoreni** [pinojs/pino-socket#6]
pino-socket exits gracefully even if the underlying node process exited with an error.

Is it possible to propagate the exit status so that we can recognize a fail externally?

**Comment by jsumners** [comment]
I'm not sure how you expect that to happen. `pino-socket` is merely a tool your application pipes into. The pipe doesn't propagate exit codes.

If you are using Bash as your shell then you can use the [`$PIPESTATUS`](http://www.tldp.org/LDP/abs/html/internalvariables.html#PIPESTATUSREF) variable to check your exit codes.

**Comment by mcollina** [comment]
I think forwarding the exit code might be a useful feature behind a flag,
if we can know.
Il giorno gio 10 ago 2017 alle 14:51 James Sumners <notifications@github.com>
ha scritto:

**Comment by jsumners** [comment]
@mcollina without being a process supervisor there isn't any way to know what the upstream program's exit code is. This is something that must be handled by the parent shell.

**Comment by marcoreni** [comment]
I did some further testing using the $PIPESTATUS suggestion.

My issue is that I'm wrapping the piping inside an npm script: `"start": "node ./index.js | pino-socket"`. 
```javascript
// index.js
process.on('exit', function(code) {
  console.log('About to exit with code:', code);
});
test = 1 / nah;
```

This script always returns `0` (please note last line):
```shell
reni@DESKTOP-84H1L9I:/test-pinosocket$ npm run-script start ; echo $PIPESTATUS

> @ start-pino /test-pinosocket
> node ./index.js | pino-socket

/test-pinosocket/index.js:4
test = 1 / nah;
           ^

ReferenceError: nah is not defined
    at Object.<anonymous> (/test-pinosocket/index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
About to exit with code: 1
0
```

Piping in shell yields correct result:
```shell
reni@DESKTOP-84H1L9I:/test-pinosocket$ node index.js | ./node_modules/.bin/pino-socket ; echo $PIPESTATUS
/test-pinosocket/index.js:4
test = 1 / nah;
           ^

ReferenceError: nah is not defined
    at Object.<anonymous> (/test-pinosocket/index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
About to exit with code: 1
1
```

I tried handling using [set -o pipefail](https://durak.org/sean/pubs/software/bash-4.1/bashref_17.html#SEC62) inside the script, but since I'm using Debian this option is not available. 

My node process is running inside Docker and I have an external system that monitors the process and it's exit code. Is there a way to have the correct exit code exposed?

**Comment by jsumners** [comment]
`PIPESTATUS` is an array, so you need to `echo ${PIPESTATUS[@]}` to view the contents of the array.

To do what you're wanting, you will need to start the process via a shell script that can deal with the pipe and statuses. That shell script will be the thing that returns the exit code.

**Comment by davidmarkclements** [comment]
ok I love that I'm learning a new thing here

```
$ exit 1 | exit 2 | echo ${PIPESTATUS[@]}
1 2 0
```

I guess that means echo's return code

```sh
$ exit 1 | exit 2 | echo ${PIPESTATUS[0]}
1
```

neato!

```sh
$ exit 1 | exit 2 | echo ${PIPESTATUS[1]}
2
```

oh yah cool this is def. neato

```js
$ exit 1 | exit 2 | echo ${PIPESTATUS[2]}
0
```

hooray, echo return code (same as @ it seems?)

```sh
$ exit 1 | exit 2 | echo ${PIPESTATUS[3]}

```

gives a blank result, excellent

```sh
$ exit 1 | exit 2 | echo $PIPESTATUS
1
```

...ok so just the variable gives the 0 index, makes sense

```sh
exit 1 | exit 2 | node -p "process.env.PIPESTATUS"
undefined
```

awwww

```sh
exit 1 | exit 2 | node -p "child_process.execSync('echo $PIPESTATUS')+''"
1
```

oooh 🤔
