### ISSUE TITLE
Logs are not sent if the TCP server wasn't available when the logger was initialized

### ISSUE THREAD

**Issue by Mogztter** [pinojs/pino-socket#73]
It seems that `pino-socket` can reconnect to a TCP server (using the `reconnect` option) but if the TCP server wasn't available when the logger (multistream?) was initialized then the server won't receive any data.

I've created a simple reproduction case because it's hard to explain but relatively straightforward to reproduce: https://github.com/Mogztter/pino-socket-reconnect

My observations:
- `pino-socket` successfully reconnect (connect) to the TCP server and stops sending `connect ECONNREFUSED 127.0.0.1:13370` as soon as the server is started
- `stream.write(data)` in `multistream` is called
- `ThreadStream.write` is called but `writeSync` is not, we keep calling `nextFlush`
- the `write` function defined on the `outputStream` in `TcpConnection` is not called

Hopefully, I didn't miss something obvious 😅

**Comment by Mogztter** [comment]
> This should be fixed in pino-socket, moving it there.

I cannot reproduce this issue when using `TcpConnection` directly.

> Remember to add unit tests.

I can add a unit test to demonstrate that `TcpConnection` can reconnect even if the TCP server wasn't available at the start.

**Comment by Mogztter** [comment]
I think I found two issues!

The first one is that we shouldn't emit an `error` on the writable stream when `reconnect` is true (because it's a recoverable error). Otherwise, thread-stream will destroy the stream/worker.

The second one is that we do not emit `outputStream.emit('open', socket.address())` when we reconnect. If the initial `connect` fails then we won't emit `open` and as a result we won't receive any data.

Here's the initial connect:

https://github.com/pinojs/pino-socket/blob/7db92b448d90e92ba3cc922654a509cef40be44c/lib/TcpConnection.js#L198-L200

And here's the reconnect where we do not emit `open`:

https://github.com/pinojs/pino-socket/blob/7db92b448d90e92ba3cc922654a509cef40be44c/lib/TcpConnection.js#L206-L213

Is it OK to emit an `open` event every time we connect or reconnect?

**Comment by mcollina** [comment]
Yes it should be ok to emit open multiple times
