### ISSUE TITLE
Hot to send to fluentbit directly in application / no stdout piping

### ISSUE THREAD

**Issue by mhf-ir** [pinojs/pino-socket#8]
[Article for use case](https://dzone.com/articles/fluentd-vs-fluent-bit-side-by-side-comparison-logz)
Fluentbit is very lightweight zero dependency log collector best use case is store edge of logs tag them and interval flush to next log level aggregation 

How can i path throw logs to fluentd via pino:
Heres my file storage method:
```typescript
import { createWriteStream, existsSync, mkdirSync } from 'fs';
import { tmpdir } from 'os';

import * as pino from 'pino';

export default () => {
  const dir = `${tmpdir()}/logs`;
  if (!existsSync(dir)) {
    mkdirSync(dir);
  }
  const stream = createWriteStream(`${dir}/aasaam-app.log`, {
    flags: 'a+',
  });
  const logger = pino(stream);
  return logger;
};
```
For example above i can use input-tail plugin for fluentbit but if logs can directly into fluentbit tcp server will be awesome :smile: 

I need to do with script not using terminal piping and how to send json logs to fluentbit server:
https://fluentbit.io/documentation/0.14/input/tcp.html

**Comment by jsumners** [comment]
This module is designed to receive input on `stdin` and that is the recommendation when using Pino. If you want to ship logs to an external service, look at using something like [logagent](https://sematext.com/logagent/).

Closing this as it is off-topic for the `pino-socket` module.
