### ISSUE TITLE
Allow to configure the backoff strategy using primitive data types

### ISSUE THREAD

**Issue by Mogztter** [pinojs/pino-socket#84]
Since functions cannot be serialized across worker thread boundaries, the following won't work when using pino socket with `multistream`/`ThreadStream`:

```js
const socketStream = pino.transport({
    target: "pino-socket",
    options: {
        address: tcpAddress,
        port: tcpPort,
        mode: "tcp",
        reconnect: true,
        reconnectTries: 2,
        backoffStrategy: new ExponentialStrategy({})
    }
})
```

I think it might be useful to configure the backoff strategy using primitive data types.
The `backoff` library provides two backoff strategies:

- `exponential`
- `fibonacci` (default)

Exponential backoff has the following options:

- randomisationFactor: defaults to 0, must be between 0 and 1
- initialDelay: defaults to 100 ms
- maxDelay: defaults to 10000 ms
- factor: defaults to 2, must be greater than 1

Fibonacci backoff has the following options:

- randomisationFactor: defaults to 0, must be between 0 and 1
- initialDelay: defaults to 100 ms
- maxDelay: defaults to 10000 ms

I think we can keep the `backoffStrategy` option when you want to pass a custom strategy and/or when you are not using pino socket with `multistream`/`ThreadStream`.

I propose to add the following options:

- `backoffStrategyName` (string): Name of the backoff strategy, either `exponential` or `fibonacci` (default `fibonacci`)
- `backoffStrategyOptions` (object): Backoff strategy options

If both `backoffStrategyName`/`backoffStrategyOptions` AND `backoffStrategy` are defined then `backoffStrategy` will prevail (i.e., `backoffStrategyName` and `backoffStrategyOptions` will be ignored).

**Comment by mcollina** [comment]
I would rather use the same property for both cases.

**Comment by Mogztter** [comment]
> I would rather use the same property for both cases.

Something like this?

```js
// custom backoff strategy
const socketStream = pino.transport({
  target: "pino-socket",
  options: {
    backoffStrategy: new CustomStrategy({})
  }
})
```

```js
// built-in strategy with custom options
const socketStream = pino.transport({
  target: "pino-socket",
  options: {
    backoffStrategy: {
      name: "exponential",
      options: {
        initialDelay: 200,
        randomisationFactor: 0.5,
      }
    }
  }
})
```

**Comment by mcollina** [comment]
yes!
