### ISSUE TITLE
Uncaught exception 'send EMSGSIZE'

### ISSUE THREAD

**Issue by asc11cat** [pinojs/pino-socket#91]
If we will try to send a UDP packet which is over the OS MTU limit, we will face the uncaught exception 'Error: send EMSGSIZE' from dgram. 

To prevent this from happening, we could use some type of a custom limit, which can be defined manually in transport options. I created a draft of this limit in https://github.com/pinojs/pino-socket/pull/90, but I also see a possible problem with this approach:

As can be seen in test case '[udp packet overflow - skip packet when using max packet size option](https://github.com/pinojs/pino-socket/pull/90/files#diff-665f3f5bf4e46ccdd19451b8656e5719d66d2a8568af59d9463240bcb05052ccR183)', before sending another packet we either need to wait or to flush the transport for test to work correctly, otherwise no packet will be received at all, and test will fail on timeout. As I see, this is happening because multiple logs can be joined in one buffer and passed to socket.send() together(later processed internally by dgram?).

  Therefore, if we are skipping one packet, this can theoretically cancel the send of others which was already joined by this time. So we need to know if there is a way to remove only the 'overflow' packet, and most importantly, to do it without modifying the logic outside of the pino-socket transport.  We also must keep in mind that we are operating on a stream of data.

Testcase that reproduces this error - [here](https://github.com/pinojs/pino-socket/pull/90/files#diff-665f3f5bf4e46ccdd19451b8656e5719d66d2a8568af59d9463240bcb05052ccR145)

I would appreciate any suggestions on how we should handle this, so I can work on the optimal fix

**Comment by asc11cat** [comment]
@jsumners @mcollina

**Comment by jsumners** [comment]
We get notifications of all issues filed. You do not need to ping us directly.

Thank you for the PR to solve the issue.

**Comment by asc11cat** [comment]
> We get notifications of all issues filed. You do not need to ping us directly.
> 
> Thank you for the PR to solve the issue.
Sorry, forgot about that, my bad

One thing about the PR, do you think that this 'limit' implementation is enough, or there is a better way in that case? The main thing that concerns me is the possible effect of this limit on other logs, that I described earlier in the issue.

**Comment by jsumners** [comment]
> One thing about the PR, do you think that this 'limit' implementation is enough, or there is a better way in that case? The main thing that concerns me is the possible effect of this limit on other logs, that I described earlier in the issue.

I cannot answer this question without doing research, and I do not have time for that. What I'll say is that there is no such thing as a "udp stream":

https://en.wikipedia.org/wiki/User_Datagram_Protocol
> It has no [handshaking](https://en.wikipedia.org/wiki/Handshaking) dialogues, and thus exposes the user's program to any [unreliability](https://en.wikipedia.org/wiki/Reliability_(computer_networking)) of the underlying network; there is no guarantee of delivery, ordering, or duplicate protection. If error-correction facilities are needed at the network interface level, an application may instead use [Transmission Control Protocol](https://en.wikipedia.org/wiki/Transmission_Control_Protocol) (TCP) or [Stream Control Transmission Protocol](https://en.wikipedia.org/wiki/Stream_Control_Transmission_Protocol) (SCTP) which are designed for this purpose.

The inclusion of UDP in this module is to facilitate standard syslog message sending with `pino-syslog`. When sending data with UDP it is up to the application to make sure the data is sent in a way that it can be received as desired.

**Comment by asc11cat** [comment]
> > One thing about the PR, do you think that this 'limit' implementation is enough, or there is a better way in that case? The main thing that concerns me is the possible effect of this limit on other logs, that I described earlier in the issue.
> 
> I cannot answer this question without doing research, and I do not have time for that. What I'll say is that there is no such thing as a "udp stream":
> 
> https://en.wikipedia.org/wiki/User_Datagram_Protocol
> 
> > It has no [handshaking](https://en.wikipedia.org/wiki/Handshaking) dialogues, and thus exposes the user's program to any [unreliability](https://en.wikipedia.org/wiki/Reliability_(computer_networking)) of the underlying network; there is no guarantee of delivery, ordering, or duplicate protection. If error-correction facilities are needed at the network interface level, an application may instead use [Transmission Control Protocol](https://en.wikipedia.org/wiki/Transmission_Control_Protocol) (TCP) or [Stream Control Transmission Protocol](https://en.wikipedia.org/wiki/Stream_Control_Transmission_Protocol) (SCTP) which are designed for this purpose.
> 
> The inclusion of UDP in this module is to facilitate standard syslog message sending with `pino-syslog`. When sending data with UDP it is up to the application to make sure the data is sent in a way that it can be received as desired.

By stream I was meaning the Writable stream at https://github.com/pinojs/pino-socket/blob/master/lib/UdpConnection.js#L25 which theoretically could cause the problem that I described. 

But I understand the time concerns, ill try to check it be myself later and see if I can find something, thanks
